//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XSC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XSC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command line parameter: {0}
        ///Use something like this: 
        ///XSC.exe [address|private key]
        ///
        ///For instance:
        ///XSC.exe AkkCpnFFy8PgDdS5jpE2D8
        ///XSC.exe 4543533220000000D225B2E78BEAAFC93673E480102B42F3B2A4D6A62D40C95A42A0C3E7C38B495AB942EB76CDF34001884695B501E4B7B3D24784F59419D7BA397DD4EFA555EDA4F3488226D6252E6A663B4A9B6C77696D4520C7F5D7AAD597159A9DB951BD09A5
        ///.
        /// </summary>
        public static string ArgumentException {
            get {
                return ResourceManager.GetString("ArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB Created, using: {0}.
        /// </summary>
        public static string DbCreated {
            get {
                return ResourceManager.GetString("DbCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB Info: Address: {0}, Balance: {1}, Height: {2} .
        /// </summary>
        public static string DbInfo {
            get {
                return ResourceManager.GetString("DbInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB Loading, using: {0}.
        /// </summary>
        public static string DbLoading {
            get {
                return ResourceManager.GetString("DbLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB Loaded successfully.
        /// </summary>
        public static string DbOpened {
            get {
                return ResourceManager.GetString("DbOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception ({0}): {1}.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough funds.
        /// </summary>
        public static string ExceptionNotEnoughFunds {
            get {
                return ResourceManager.GetString("ExceptionNotEnoughFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG Initialized, using: {0}.
        /// </summary>
        public static string LogInitialized {
            get {
                return ResourceManager.GetString("LogInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NODE Started internal miner.
        /// </summary>
        public static string NodeStartMining {
            get {
                return ResourceManager.GetString("NodeStartMining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NODE Started P2P service: {0}.
        /// </summary>
        public static string NodeStartService {
            get {
                return ResourceManager.GetString("NodeStartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NODE Start synchronizing.
        /// </summary>
        public static string NodeStartSynchronizing {
            get {
                return ResourceManager.GetString("NodeStartSynchronizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NODE Synchronization has completed.
        /// </summary>
        public static string NodeSynchronized {
            get {
                return ResourceManager.GetString("NodeSynchronized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NODE Waiting for other peers.
        /// </summary>
        public static string NodeWaitingPeers {
            get {
                return ResourceManager.GetString("NodeWaitingPeers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P2P Exception: {0}.
        /// </summary>
        public static string P2PException {
            get {
                return ResourceManager.GetString("P2PException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help: Shows this help
        ///exit: Terminates the application
        ///
        ///address: Shows your address
        ///balance: Shows your balance
        ///transfer [address] [amount]: Transfers coins
        ///
        ///geth: Gets current blockchain height
        ///getb [height or hash]: Gets a block by height or hash
        ///gett [hash]: Gets a transaction by hash
        ///getp: Gets a list of connected peers
        ///getm: Shows pending transactions.
        /// </summary>
        public static string ShellHelp {
            get {
                return ResourceManager.GetString("ShellHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to XSC Shell, type &quot;help&quot; to get a list of all available commands.
        /// </summary>
        public static string ShellWelcome {
            get {
                return ResourceManager.GetString("ShellWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WALLET Created, using: {0}.
        /// </summary>
        public static string WalletCreated {
            get {
                return ResourceManager.GetString("WalletCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WALLET Opened, using: {0}.
        /// </summary>
        public static string WalletOpened {
            get {
                return ResourceManager.GetString("WalletOpened", resourceCulture);
            }
        }
    }
}
